import turtle
tata=turtle.Turtle()
tata.shape("turtle")
tamanho=turtle.numinput("ATENÇÃO!", "Digite o tamanho do lado: ")
cor=(turtle.textinput("ATENÇÃO!","Digite a cor em inglês: "))
tata.color(cor)
tata.begin_fill()
tata.forward(tamanho)
tata.left(120)
tata.forward(tamanho)
tata.left(120)
tata.forward(tamanho)
tata.left(120)
tata.end_fill()
tata.hideturtle()
turtle.done()